### PR TITLE
use global post to get ID

### LINKED ISSUE #1: Undefined variable
screenshot 2015-01-09 09 30 41

### PR DESCRIPTION
**Pull request by pdewouters**
@joehoyle not sure this is the correct way to do it

Fixes https://github.com/humanmade/wpthumb-bridge/issues/1

### CODE REVIEW

**Comment by willmot** [comment]
You can just use `get_post_id()`

**Comment by pdewouters** [comment]
I was thinking about cases outside the loop too

**Comment by willmot** [comment]
You can use `get_the_id()` outside the loop, it just wraps `get_post()->ID` and internally `get_post()` uses `global $post` if an ID isn't passed in.

**Comment by pdewouters** [comment]
fancy that! the notion was stuck in my mind

**Comment by willmot** [comment]
@joehoyle running into this too, can this be merged?

**Comment by willmot** [comment]
Merging, feel free to revert if it's an issue.

**Pull request merged**
